/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BlogArticleEditWebModel } from '../models';
import { BlogArticleWebModelApiResult } from '../models';
import { BlogArticleWebModelListApiResult } from '../models';
import { BlogArticleWebModelPageViewModelApiResult } from '../models';
import { StringApiResult } from '../models';
/**
 * BlogArticleApi - axios parameter creator
 * @export
 */
export const BlogArticleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取博客文章列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticleGetListGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/BlogArticle/GetList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取博客文章分页
         * @param {number} [pageIndex] 当前页数
         * @param {number} [pageSize] 分页大小
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticleGetPageGet: async (pageIndex?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/BlogArticle/GetPage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除博客文章 (Auth)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticleIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV1BlogArticleIdDelete.');
            }
            const localVarPath = `/api/v1/BlogArticle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取博客文章详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticleIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV1BlogArticleIdGet.');
            }
            const localVarPath = `/api/v1/BlogArticle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新博客文章 (Auth)
         * @param {number} id 
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticleIdPut: async (id: number, body?: BlogArticleEditWebModel, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV1BlogArticleIdPut.');
            }
            const localVarPath = `/api/v1/BlogArticle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 添加博客文章 (Auth)
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlogArticlePost: async (body?: BlogArticleEditWebModel, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/BlogArticle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlogArticleApi - functional programming interface
 * @export
 */
export const BlogArticleApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取博客文章列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleGetListGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BlogArticleWebModelListApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticleGetListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取博客文章分页
         * @param {number} [pageIndex] 当前页数
         * @param {number} [pageSize] 分页大小
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleGetPageGet(pageIndex?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BlogArticleWebModelPageViewModelApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticleGetPageGet(pageIndex, pageSize, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 删除博客文章 (Auth)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StringApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticleIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取博客文章详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BlogArticleWebModelApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticleIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 更新博客文章 (Auth)
         * @param {number} id 
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdPut(id: number, body?: BlogArticleEditWebModel, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StringApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticleIdPut(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 添加博客文章 (Auth)
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticlePost(body?: BlogArticleEditWebModel, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StringApiResult>>> {
            const localVarAxiosArgs = await BlogArticleApiAxiosParamCreator(configuration).apiV1BlogArticlePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BlogArticleApi - factory interface
 * @export
 */
export const BlogArticleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取博客文章列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleGetListGet(options?: AxiosRequestConfig): Promise<AxiosResponse<BlogArticleWebModelListApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticleGetListGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取博客文章分页
         * @param {number} [pageIndex] 当前页数
         * @param {number} [pageSize] 分页大小
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleGetPageGet(pageIndex?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<BlogArticleWebModelPageViewModelApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticleGetPageGet(pageIndex, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除博客文章 (Auth)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<StringApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticleIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取博客文章详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<BlogArticleWebModelApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticleIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新博客文章 (Auth)
         * @param {number} id 
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticleIdPut(id: number, body?: BlogArticleEditWebModel, options?: AxiosRequestConfig): Promise<AxiosResponse<StringApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticleIdPut(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 添加博客文章 (Auth)
         * @param {BlogArticleEditWebModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlogArticlePost(body?: BlogArticleEditWebModel, options?: AxiosRequestConfig): Promise<AxiosResponse<StringApiResult>> {
            return BlogArticleApiFp(configuration).apiV1BlogArticlePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlogArticleApi - object-oriented interface
 * @export
 * @class BlogArticleApi
 * @extends {BaseAPI}
 */
export class BlogArticleApi extends BaseAPI {
    /**
     * 
     * @summary 获取博客文章列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticleGetListGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<BlogArticleWebModelListApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticleGetListGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取博客文章分页
     * @param {number} [pageIndex] 当前页数
     * @param {number} [pageSize] 分页大小
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticleGetPageGet(pageIndex?: number, pageSize?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<BlogArticleWebModelPageViewModelApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticleGetPageGet(pageIndex, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 删除博客文章 (Auth)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticleIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<StringApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticleIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取博客文章详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticleIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<BlogArticleWebModelApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticleIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 更新博客文章 (Auth)
     * @param {number} id 
     * @param {BlogArticleEditWebModel} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticleIdPut(id: number, body?: BlogArticleEditWebModel, options?: AxiosRequestConfig) : Promise<AxiosResponse<StringApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticleIdPut(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 添加博客文章 (Auth)
     * @param {BlogArticleEditWebModel} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogArticleApi
     */
    public async apiV1BlogArticlePost(body?: BlogArticleEditWebModel, options?: AxiosRequestConfig) : Promise<AxiosResponse<StringApiResult>> {
        return BlogArticleApiFp(this.configuration).apiV1BlogArticlePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
