/* tslint:disable */
/* eslint-disable */
/**
 * Larxyoung.Blog API V1
 * Larxyoung.Blog 接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { LoginWebModel } from '../models';
import { RESTfulResultBoolean } from '../models';
import { RESTfulResultString } from '../models';
import { RESTfulResultTokenWebModel } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 登录
         * @param {LoginWebModel} [body] 登录入参WebModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BaseAuthLogin10Post: async (body?: LoginWebModel, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/BaseAuth/Login@1.0`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 是否启用登录验证码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BaseAuthLoginShowCaptcha10Get: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/BaseAuth/LoginShowCaptcha@1.0`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取登录图片验证码
         * @param {string} id 该次登录唯一标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BaseAuthLoginVerifyCode10IdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV1BaseAuthLoginVerifyCode10IdGet.');
            }
            const localVarPath = `/api/v1/BaseAuth/LoginVerifyCode@1.0/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 登录
         * @param {LoginWebModel} [body] 登录入参WebModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLogin10Post(body?: LoginWebModel, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultTokenWebModel>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiV1BaseAuthLogin10Post(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 是否启用登录验证码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLoginShowCaptcha10Get(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultBoolean>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiV1BaseAuthLoginShowCaptcha10Get(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取登录图片验证码
         * @param {string} id 该次登录唯一标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLoginVerifyCode10IdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultString>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiV1BaseAuthLoginVerifyCode10IdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 登录
         * @param {LoginWebModel} [body] 登录入参WebModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLogin10Post(body?: LoginWebModel, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultTokenWebModel>> {
            return DefaultApiFp(configuration).apiV1BaseAuthLogin10Post(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 是否启用登录验证码
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLoginShowCaptcha10Get(options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultBoolean>> {
            return DefaultApiFp(configuration).apiV1BaseAuthLoginShowCaptcha10Get(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取登录图片验证码
         * @param {string} id 该次登录唯一标识
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BaseAuthLoginVerifyCode10IdGet(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultString>> {
            return DefaultApiFp(configuration).apiV1BaseAuthLoginVerifyCode10IdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 登录
     * @param {LoginWebModel} [body] 登录入参WebModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public async apiV1BaseAuthLogin10Post(body?: LoginWebModel, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultTokenWebModel>> {
        return DefaultApiFp(this.configuration).apiV1BaseAuthLogin10Post(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 是否启用登录验证码
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public async apiV1BaseAuthLoginShowCaptcha10Get(options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultBoolean>> {
        return DefaultApiFp(this.configuration).apiV1BaseAuthLoginShowCaptcha10Get(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取登录图片验证码
     * @param {string} id 该次登录唯一标识
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public async apiV1BaseAuthLoginVerifyCode10IdGet(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultString>> {
        return DefaultApiFp(this.configuration).apiV1BaseAuthLoginVerifyCode10IdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}
