/* tslint:disable */
/* eslint-disable */
/**
 * Larxyoung.Blog API V1
 * Larxyoung.Blog 接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RESTfulResultTestWebModel } from '../models';
/**
 * TestWebApi - axios parameter creator
 * @export
 */
export const TestWebApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取一条测试信息（内存缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TestWebTestMsgByMemoryCache10Get: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/TestWeb/TestMsgByMemoryCache@1.0`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取一条测试信息（Redis缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TestWebTestMsgByRedisCache10Get: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/TestWeb/TestMsgByRedisCache@1.0`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestWebApi - functional programming interface
 * @export
 */
export const TestWebApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取一条测试信息（内存缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TestWebTestMsgByMemoryCache10Get(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultTestWebModel>>> {
            const localVarAxiosArgs = await TestWebApiAxiosParamCreator(configuration).apiV1TestWebTestMsgByMemoryCache10Get(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取一条测试信息（Redis缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TestWebTestMsgByRedisCache10Get(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RESTfulResultTestWebModel>>> {
            const localVarAxiosArgs = await TestWebApiAxiosParamCreator(configuration).apiV1TestWebTestMsgByRedisCache10Get(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TestWebApi - factory interface
 * @export
 */
export const TestWebApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取一条测试信息（内存缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TestWebTestMsgByMemoryCache10Get(options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultTestWebModel>> {
            return TestWebApiFp(configuration).apiV1TestWebTestMsgByMemoryCache10Get(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取一条测试信息（Redis缓存）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TestWebTestMsgByRedisCache10Get(options?: AxiosRequestConfig): Promise<AxiosResponse<RESTfulResultTestWebModel>> {
            return TestWebApiFp(configuration).apiV1TestWebTestMsgByRedisCache10Get(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TestWebApi - object-oriented interface
 * @export
 * @class TestWebApi
 * @extends {BaseAPI}
 */
export class TestWebApi extends BaseAPI {
    /**
     * 
     * @summary 获取一条测试信息（内存缓存）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestWebApi
     */
    public async apiV1TestWebTestMsgByMemoryCache10Get(options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultTestWebModel>> {
        return TestWebApiFp(this.configuration).apiV1TestWebTestMsgByMemoryCache10Get(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取一条测试信息（Redis缓存）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestWebApi
     */
    public async apiV1TestWebTestMsgByRedisCache10Get(options?: AxiosRequestConfig) : Promise<AxiosResponse<RESTfulResultTestWebModel>> {
        return TestWebApiFp(this.configuration).apiV1TestWebTestMsgByRedisCache10Get(options).then((request) => request(this.axios, this.basePath));
    }
}
