/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogArticleWebModel } from './blog-article-web-model';
/**
 * 
 * @export
 * @interface BlogArticleWebModelPageViewModel
 */
export interface BlogArticleWebModelPageViewModel {
    /**
     * 
     * @type {Array<BlogArticleWebModel>}
     * @memberof BlogArticleWebModelPageViewModel
     */
    viewModelList?: Array<BlogArticleWebModel> | null;
    /**
     * 
     * @type {number}
     * @memberof BlogArticleWebModelPageViewModel
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogArticleWebModelPageViewModel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogArticleWebModelPageViewModel
     */
    totalRecords?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogArticleWebModelPageViewModel
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BlogArticleWebModelPageViewModel
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlogArticleWebModelPageViewModel
     */
    hasNextPage?: boolean;
}
