/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 登录入参 WebModel
 * @export
 * @interface LoginWebModel
 */
export interface LoginWebModel {
    /**
     * 账号
     * @type {string}
     * @memberof LoginWebModel
     */
    userName: string;
    /**
     * 密码
     * @type {string}
     * @memberof LoginWebModel
     */
    password: string;
}
