/* tslint:disable */
/* eslint-disable */
/**
 * Larxyoung.Blog API V1
 * Larxyoung.Blog 接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 登录入参WebModel
 * @export
 * @interface LoginWebModel
 */
export interface LoginWebModel {
    /**
     * 该次登录唯一标识
     * @type {string}
     * @memberof LoginWebModel
     */
    id: string;
    /**
     * 用户名
     * @type {string}
     * @memberof LoginWebModel
     */
    userName: string;
    /**
     * 密码
     * @type {string}
     * @memberof LoginWebModel
     */
    passWord: string;
    /**
     * 验证码
     * @type {string}
     * @memberof LoginWebModel
     */
    captcha?: string | null;
}
