/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 测试 WebModel
 * @export
 * @interface TestWebModel
 */
export interface TestWebModel {
    /**
     * 主键
     * @type {number}
     * @memberof TestWebModel
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof TestWebModel
     */
    cDate?: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof TestWebModel
     */
    mDate?: Date;
    /**
     * 排序
     * @type {number}
     * @memberof TestWebModel
     */
    sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof TestWebModel
     */
    remark?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof TestWebModel
     */
    name?: string | null;
}
