/* tslint:disable */
/* eslint-disable */
/**
 * Larxyoung.Blog API V1
 * Larxyoung.Blog 接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Token令牌信息
 * @export
 * @interface TokenWebModel
 */
export interface TokenWebModel {
    /**
     * 令牌
     * @type {string}
     * @memberof TokenWebModel
     */
    token?: string | null;
    /**
     * 过期时间（单位：分钟）
     * @type {number}
     * @memberof TokenWebModel
     */
    expiredTime?: number | null;
}
