/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenInfoViewModel
 */
export interface TokenInfoViewModel {
    /**
     * Token
     * @type {string}
     * @memberof TokenInfoViewModel
     */
    token?: string | null;
    /**
     * 过期时间 单位:秒 默认15分钟
     * @type {number}
     * @memberof TokenInfoViewModel
     */
    expiresIn?: number;
    /**
     * Token类型
     * @type {string}
     * @memberof TokenInfoViewModel
     */
    tokenType?: string | null;
}
