/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserWebModel } from './user-web-model';
/**
 * 
 * @export
 * @interface UserWebModelPageViewModel
 */
export interface UserWebModelPageViewModel {
    /**
     * 
     * @type {Array<UserWebModel>}
     * @memberof UserWebModelPageViewModel
     */
    viewModelList?: Array<UserWebModel> | null;
    /**
     * 
     * @type {number}
     * @memberof UserWebModelPageViewModel
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof UserWebModelPageViewModel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof UserWebModelPageViewModel
     */
    totalRecords?: number;
    /**
     * 
     * @type {number}
     * @memberof UserWebModelPageViewModel
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserWebModelPageViewModel
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserWebModelPageViewModel
     */
    hasNextPage?: boolean;
}
