/* tslint:disable */
/* eslint-disable */
/**
 * Lenceas.Core.Api 接口文档——.NET 7.0.4
 * Lenceas.Core.Api HTTP API v1
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 用户表
 * @export
 * @interface User
 */
export interface User {
    /**
     * 主键
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof User
     */
    cDate: Date;
    /**
     * 更新时间
     * @type {Date}
     * @memberof User
     */
    mDate: Date;
    /**
     * 排序
     * @type {number}
     * @memberof User
     */
    sort: number;
    /**
     * 备注
     * @type {string}
     * @memberof User
     */
    remark?: string | null;
    /**
     * 账号
     * @type {string}
     * @memberof User
     */
    userName: string;
    /**
     * 密码
     * @type {string}
     * @memberof User
     */
    password: string;
    /**
     * 邮箱
     * @type {string}
     * @memberof User
     */
    email?: string | null;
}
